#define wifiSsid "YOUR WIFI NAME"
#define wifiKey "YOUR PASSWORD"

#define INFLUXDB_URL "http://YOUR_SERVER:YOUR_PORT"
#define INFLUXDB_TOKEN "YOUR_TOKEN"
#define INFLUXDB_ORG "YOUR_ORGA"
#define INFLUXDB_BUCKET "YOUR_BUCKET_NAME"
#define DATAPOINT_NAME "YOUR_DATAPOINT_NAME"
